name: Maven Build and Goals

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build Maven Project
      run: mvn clean install -B

    - name: Display Maven Goals Output
      run: |
        mvn --version
       
       

